# Generated by Django 3.2.8 on 2021-10-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, choices=[('music production', 'music production'), ('software development', 'software development'), ('computer gaming', 'computer gaming')], max_length=100, null=True)),
                ('gendere', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('French', 'French'), ('German', 'German')], max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
